### ISSUE TITLE
(design) Make 4 icons for app

### ISSUE THREAD

**Issue by shelleywang** [Trustworthy-Hair/partyof4mobile#2]
1. Search / Filter
2. List view
3. Add new event
   4.Hamburger menu*

*Should we use Hamburger menu icon? https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/

**Comment by wrrnwng** [comment]
added 5 icons in the tab bar (1 for map). need to figure out how to change the view based on selected tab
